//
// Autogenerated file - do not edit
//

extern const unsigned char rp2040_features_xml[2326];
extern const unsigned char rp2040_memory_map_xml[274];
extern const unsigned char rp2040_threads_xml[172];
